version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:latest"
    restart: always
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    networks:
      - default 

  back:
    build: ./
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - 8089:8089
    image: anisammar422/docker:latest
    depends_on:
      - mysqldb
    networks:
      - default  # Specify the same 
